Repository wgsl-analyzer/wgsl-analyzer, pull requests merged in 2025-10, with the labels that each got.

#585 feature: Syntax highlight wgsl when /*wgsl*/ comment is encountered
  .vscode/settings.json
  docs/book/src/editor_features.md
  docs/book/src/host-code-comment.png
  docs/book/src/markdown-code-block.png
  editors/code/package.json
  editors/code/syntaxes/inline-wgsl.markdown.tmLanguage.json
  editors/code/syntaxes/inline-wgsl.tmLanguage.json
Labels: C-Feature, S-Ready-to-Review, D-Straightforward, A-Editor

#593 internal: Fix release workflow
  .github/workflows/release.yaml
Labels: C-Bug, D-Trivial, S-Ready-to-Review, A-Build-System

#597 Toml fixes
  Cargo.toml
  crates/base_db/Cargo.toml
  crates/edition/Cargo.toml
  crates/hir/Cargo.toml
  crates/hir_def/Cargo.toml
  crates/hir_ty/Cargo.toml
  crates/ide-db/Cargo.toml
  crates/ide/Cargo.toml
  crates/ide_completion/Cargo.toml
  crates/parser/Cargo.toml
  crates/profile/Cargo.toml
  crates/stdx/Cargo.toml
  crates/syntax/Cargo.toml
  crates/test-utils/Cargo.toml
  crates/toolchain/Cargo.toml
  crates/vfs-notify/Cargo.toml
  crates/wgsl-analyzer/Cargo.toml
  crates/wgsl_formatter/Cargo.toml
Labels: D-Trivial, S-Ready-to-Review, A-Cross-Cutting, C-Chore
