Repository wgsl-analyzer/wgsl-analyzer, pull requests merged in 2025-07, with the labels that each got.

#354 feature: Update tm language
  editors/code/syntaxes/wesl.tmLanguage.json
  editors/code/syntaxes/wgsl.tmLanguage.json
Labels: C-Feature, S-Ready-to-Review, D-Straightforward, A-Editor

#391 Add Contributing.md
  CONTRIBUTING.md
Labels: C-Documentation, D-Trivial, S-Ready-to-Review, A-Meta

#393 New logo
  editors/code/icon.png
  logo.svg
Labels: C-Feature, D-Trivial, S-Waiting-on-Author, A-Meta

#431 CI fixes
  .github/dependabot.yaml
  .github/workflows/ci.yaml
  editors/code/package.json
  xtask/src/dist.rs
Labels: C-Bug, D-Trivial, S-Ready-to-Review, A-Build-System, C-Chore
